on: [push, pull_request]

name: Continuous integration

jobs:
  run:
    name: Run
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
